/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ColeRouteImport } from './routes/cole'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as TiendaSlugRouteImport } from './routes/tienda.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeRoute = ColeRouteImport.update({
  id: '/cole',
  path: '/cole',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TiendaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/cole': typeof ColeRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/admin/productos': typeof AdminProductosRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/cole': typeof ColeRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/admin/productos': typeof AdminProductosRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/cole': typeof ColeRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/admin/productos': typeof AdminProductosRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/cole'
    | '/contacto'
    | '/favoritos'
    | '/sobre'
    | '/tienda'
    | '/admin/productos'
    | '/tienda/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/checkout'
    | '/cole'
    | '/contacto'
    | '/favoritos'
    | '/sobre'
    | '/tienda'
    | '/admin/productos'
    | '/tienda/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/cole'
    | '/contacto'
    | '/favoritos'
    | '/sobre'
    | '/tienda'
    | '/admin/productos'
    | '/tienda/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRoute
  ColeRoute: typeof ColeRoute
  ContactoRoute: typeof ContactoRoute
  FavoritosRoute: typeof FavoritosRoute
  SobreRoute: typeof SobreRoute
  TiendaRoute: typeof TiendaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cole': {
      id: '/cole'
      path: '/cole'
      fullPath: '/cole'
      preLoaderRoute: typeof ColeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof TiendaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProductosRoute: typeof AdminProductosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductosRoute: AdminProductosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TiendaRouteChildren {
  TiendaSlugRoute: typeof TiendaSlugRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaSlugRoute: TiendaSlugRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRoute,
  ColeRoute: ColeRoute,
  ContactoRoute: ContactoRoute,
  FavoritosRoute: FavoritosRoute,
  SobreRoute: SobreRoute,
  TiendaRoute: TiendaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
